### ISSUE TITLE
Crash after aws-crt-cpp uninitialized

### ISSUE THREAD

**Issue by kankri** [awslabs/aws-crt-cpp#190]
A crash happens in version v0.10.7 when `aws-crt-cpp` is uninitialized and then the DLL using the SDK is unloaded. This does not happen in v0.10.2.

The issue can be reproduced by modifying the [`basic_pub_sub`](https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/master/samples/mqtt/basic_pub_sub/main.cpp) sample to be a DLL with the following code change:

```diff
diff --git a/samples/mqtt/basic_pub_sub/main.cpp b/samples/mqtt/basic_pub_sub/main.cpp
index 09ecd27..eb3337c 100644
--- a/samples/mqtt/basic_pub_sub/main.cpp
+++ b/samples/mqtt/basic_pub_sub/main.cpp
@@ -78,6 +78,7 @@ char *s_getCmdOption(char **begin, char **end, const String &option)
     return 0;
 }
 
+extern "C" __declspec(dllexport)
 int main(int argc, char *argv[])
 {
 
```

and changing `CMakeLists.txt` to build the file as a DLL:

```
add_library(basicpubsub SHARED main.cpp)
```

Then use a simple runner to load and run the sample code:

```c++
#include <stdio.h>
#include <windows.h>
typedef int (WINAPI *fn_main_t)(int argc, char *argv[]);

int main(int argc, char *argv[])
{
    HMODULE dll = LoadLibraryW(L"basicpubsub.dll");
    fn_main_t fn_main = (fn_main_t)GetProcAddress(dll, "main");
    int ret = fn_main(argc, argv);
    BOOL status = FreeLibrary(dll);
    Sleep(60*1000);
    return ret;
}
```

When running this using version `v0.10.7` of the SDK, and typing "exit" to the input prompt, the following crash happens as soon as the DLL is unloaded and the main thread is in the `Sleep()` call, when the SDK tries to execute code from the unloaded DLL:

```
(43d8.9358): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
<Unloaded_basicpubsub.dll>+0x17845e:
00007ffd`ed59845e ??              ???
```

After loading the DLL back to memory the call stack can be viewed:

```
0:004> lmvm basicpubsub.dll
start             end                 module name

Unloaded modules:
00007ffd`ed420000 00007ffd`ed71c000   basicpubsub.dll
    Timestamp: Thu Oct  8 18:36:53 2020 (5F7F3215)
    Checksum:  00000000
    ImageSize:  002FC000
0:004> .reload basicpubsub.dll=00007ffd`ed420000,002FC000
0:004> kP
 # Child-SP          RetAddr           Call Site
00 000000e0`52dfe920 00007ffd`ed6dd8a0 basicpubsub!aws_thread_launch(
			struct aws_thread * thread = 0x000000e0`52dfe998, 
			<function> * func = 0x00007ffd`ed5351a0, 
			void * arg = 0x0000029a`94529dc0, 
			struct aws_thread_options * options = 0x000000e0`52dfe9d8)+0xce [crt\aws-c-common\source\windows\thread.c @ 107]
01 000000e0`52dfe928 00000000`00000001 basicpubsub!default_allocator
02 000000e0`52dfe930 00000000`00000020 0x1
03 000000e0`52dfe938 cccccccc`cccccccc 0x20
04 000000e0`52dfe940 cccccccc`00000000 0xcccccccc`cccccccc
05 000000e0`52dfe948 000000e0`52dfe9b0 0xcccccccc`00000000
06 000000e0`52dfe950 00000000`00000000 0x000000e0`52dfe9b0
```

The stack isn't very sensible, but the top frame shows that a thread is executing in `aws_thread_launch()`.

It seems that at the end of `basicpubsub!main` the destructors didn't clean up all the SDK resources.

This is hurting us badly, since version `v0.10.2` has other problems (too long Windows paths, TLS timeout issues, ...) and can't be used either.

**Comment by bretambrose** [comment]
We reworked the asynchronous shutdown/cleanup of a number of types in the C libraries a month or two back.  One part of that was the addition of a function that would work as a global wait for every known thread or event loop based object to shutdown.  Originally this method was called by the API class destructor but we changed our mind at the last second (thinking that people would be unhappily surprised at a blocking wait of unknown duration in a destructor) and moved it to a test method (since we needed it for all the tests): https://github.com/awslabs/aws-crt-cpp/blob/master/tests/Utils.h#L16

Clearly that wasn't the right decision and we should figure something out that would make it easy for users to get that kind of a wait behavior in their programs.

First possibility that jumps to mind is a possible flag in the API object that controls blocking or non-blocking shutdown with a safe (blocking) default.

**Comment by kankri** [comment]
Thanks for the background information!

> First possibility that jumps to mind is a possible flag in the API object that controls blocking or non-blocking shutdown with a safe (blocking) default.

That sounds like a good way to keep the default behavior safe and would be fine for us.

For the opt-in, non-blocking case, it might be nice to have a way to wait (maybe with timeout and ability to call the wait function repeatedly) to be able to do a controlled cleanup without indefinitely blocking. (In another project we give each module a limited time to clean up, but if it takes too long, we kill the whole process and restart to avoid hanging or being in inconsistent state.)

**Comment by kankri** [comment]
Any update on this? I thought it would be simple to move back the code from the test method to restore the previous safe operation?

**Comment by bretambrose** [comment]
Release 1.9.0 of the SDK or 0.11.0 contains a new option in the ApiHandle for blocking shutdown.  Let us know if this does not fix the problem.

**Comment by kankri** [comment]
Just as a heads-up, we are still having some problems with the issue.

I tested the new release with my repro code and it was working OK. We integrated that version into our product and while initially TA was fine, we have since been getting occasionally crashes which again point to a thread executing aws-crt-cpp code in an unloaded DLL.

It seems that the wait functionality is not waiting for all the threads started by aws-crt-cpp. I haven't been able to reproduce the issue yet outside our product TA environment. I'll let you know once I found out more.

**Comment by rccarper** [comment]
Hello, sorry that you're still running into this.  We've re-opened this issue to resume investigation on our side.

**Comment by bretambrose** [comment]
We won't be able to make additional headway on this without additional information -- ideally a sample app that reproduces the problem as well as platform/environment details.

**Comment by kankri** [comment]
So far I haven't been able to reproduce the problem outside our TA environment where it happens frequently, but I haven't had the moment to better replicate the test scenario. I will try to make that happen.

My hunch is that the problem might be related to e.g. timeouts or other error paths in which case our code would quickly unload the DLL where aws-crt is running.

We are currently running aws-crt v0.10.2 with some increased timeouts taken from v0.10.3 and it doesn't exhibit the problem.

**Comment by kankri** [comment]
I had now the chance to debug and analyze the problem for you. As mentioned earlier, in our code the
issue was related to error conditions, but in general is poised to happen any time the SDK is shut
down and unloaded.

I can reproduce the crash quite reliably as part of a bigger application, but only seldomly in a small
program taking the same steps. The issue is timing and scheduling related and seems to occur more
frequently when there are other threads with activity.

After using the SDK, the top-level function of our code exits which triggers the destruction of
`Mqtt::MqttConnection`, `Mqtt::MqttClient`, `Io::ClientBootstrap`, `Io::DefaultHostResolver`,
`Io::EventLoopGroup` and `ApiHandle`. During those steps the following happens:

1. The `resolver_thread_fn` exits
    ```
    0:024> k
     # Call Site
    00 dll!resolver_thread_fn+0x4f8 [aws-c-io\source\host_resolver.c @ 758]
    01 dll!thread_wrapper_fn+0x5b [aws-c-common\source\windows\thread.c @ 37]
    02 KERNEL32!BaseThreadInitThunk+0x14
    03 ntdll!RtlUserThreadStart+0x21
    ```
3. Its at-exit function `s_on_host_entry_shutdown_completion` is called:
   ```
   0:024> k
    # Call Site
   00 dll!s_on_host_entry_shutdown_completion [aws-c-io\source\host_resolver.c @ 248]
   01 dll!thread_wrapper_fn+0x9b [aws-c-common\source\windows\thread.c @ 48]
   02 KERNEL32!BaseThreadInitThunk+0x14
   03 ntdll!RtlUserThreadStart+0x21
   ```
4. It calls `s_cleanup_default_resolver` but is tail-call optimized, so
   `s_on_host_entry_shutdown_completion` disappears from the stack:
   ```
   0:024> k
    # Call Site
   00 dll!s_cleanup_default_resolver [aws-c-io\source\host_resolver.c @ 167]
   01 dll!thread_wrapper_fn+0x9b [aws-c-common\source\windows\thread.c @ 48]
   02 KERNEL32!BaseThreadInitThunk+0x14
   03 ntdll!RtlUserThreadStart+0x21
   ```
5. That tail-calls to `aws_global_thread_creator_decrement`:
   ```
   0:024> k
    # Call Site
   00 dll!aws_global_thread_creator_decrement [aws-c-common\source\ref_count.c @ 43]
   01 dll!thread_wrapper_fn+0x9b [aws-c-common\source\windows\thread.c @ 48]
   02 KERNEL32!BaseThreadInitThunk+0x14
   03 ntdll!RtlUserThreadStart+0x21
   ```
6. That finally tail-calls `aws_condition_variable_notify_all(&s_global_thread_signal)`:
   ```
   0:024> k
    # Call Site
   00 ntdll!NtAlertThreadByThreadId+0x14
   01 ntdll!RtlWakeAllConditionVariable+0x62
   02 dll!aws_condition_variable_notify_all+0xa [aws-c-common\source\windows\condition_variable.c @ 39]
   03 dll!thread_wrapper_fn+0x9b [aws-c-common\source\windows\thread.c @ 48]
   04 KERNEL32!BaseThreadInitThunk+0x14
   05 ntdll!RtlUserThreadStart+0x21
   ```
7. Meanwhile the main thread which was waiting in `~ApiHandle()` for that condition variable to be
   notified gets woken up:
   ```
   0:009> k
    # Call Site
   00 KERNELBASE!SleepConditionVariableSRW
   01 dll!aws_condition_variable_wait+0x13 [aws-c-common\source\windows\condition_variable.c @ 46]
   02 dll!aws_condition_variable_wait_pred+0x3c [aws-c-common\source\condition_variable.c @ 16]
   03 dll!aws_global_thread_creator_shutdown_wait+0x2d [aws-c-common\source\ref_count.c @ 67]
   04 dll!Aws::Crt::ApiHandle::~ApiHandle+0x14 [source\Api.cpp @ 56]
   ```
8. `ApiHandle` destructor finishes and the top level function exits and the calling code unloads the
   DLL. However, at this point the other thread is still inside `NtAlertThreadByThreadId`. When it
   finally gets scheduled, it returns to `dll!aws_condition_variable_notify_all`, but that code
   location is no more in the memory and causes access violation:
   ```
   (1e88.5c4): Access violation - code c0000005
   0:024> k
    # Call Site
   00 0x00007ffd`f847849a
   01 0x0000022c`f5424d20
   02 0x00007ffd`00000000
   03 0x0000022c`f53d15f0
   ```

The root cause of the crash is that the SDK tries to synchronize thread completion with condition
variables which contains an inherent race condition: the thread is not completed when it notifies
the condition variable, it still needs to exit from the thread routine.

Instead `~ApiHandle()` (and other destructors of objects owning threads) should (indirectly) call
`aws_thread_join` and `aws_thread_clean_up` for each of the threads after they have been signaled to
exit.

Finally, for safety and consistency, `ClientBootstrap` should be blocking by default and not need
a call to `ClientBootstrap::EnableBlockingShutdown()`.

**Comment by bretambrose** [comment]
This is great analysis and I apologize that you had to dig through all that in order to root cause the issue.

From a solution standpoint, I don't think we want destructors (well, the C destroy functions) calling join on threads though.  There are a couple of use cases that become problematic if we do that:
1. types like aws_host_resolver (the default one) where parent/owner/thread relationships are dynamic would require a substantial rework of the trickiest parts of their concurrency to support (and in fact the likely solution there would involve doing what I would propose to do with everything instead).  In general, we wouldn't be able to support any kind of detach-and-run.
1. I've never seen it crop up with the CPP crt, but we regularly hit situations in the other CRTs where the last reference on an event loop group is dropped from within one of its event loop threads (usually when a connection or http stream is the only escaped reference that is keeping the entire tree of objects alive transitively, and so when its io channel shuts down, the entire tree of objects gets torn down).  A join here on the event loop group threads is, naturally, a deadlock.

I think we can extend the current wait/tracking framework to solve the problem correctly for you, and doing so wouldn't change the external-facing apis or contracts.  The overall change is that we'll track a list of aws_thread objects in the thread tracker rather than just a count.  

Just doing so naively would leave us still vulnerable to the same race condition that you currently face -- in particular, if a thread exits (and removes itself from the list) right before the global shutdown wait is called, that removed thread might still be in kernel code but since it was removed from the list, no join gets done on it in the shutdown wait.

Instead, I think we can do a two-phased, lazy approach to joining.  We'll have two thread lists, active and pending_join.  Threads get added to the active list right before running and get moved from active to pending_join when their thread function exits (where we currently dec the global count).  We lazily join the pending_join list on every global thread state affecting function and we eagerly join it if global_shutdown_wait is called.  Further, the global_shutdown_wait iterates until both active and pending_join lists are simultaneously empty.  

The upshot is that every thread gets explicitly joined but the when part is somewhat arbitrary (and safe from deadlock).

The other primary change needed to make this happen is to move aws_thread from by-value usage to by-pointer.  

I think some more feasibility study needs to be done (to verify async event loop group shutdown will unwind/behave properly, and to check if aws_thread as a by-pointer object causes any issues), but that's my first take on what we should do.

**Comment by bretambrose** [comment]
Version 1.10.7 of the v2 SDK contains the new managed thread join system that we believe should address this issue.

https://github.com/aws/aws-iot-device-sdk-cpp-v2/releases/tag/v1.10.7
